// fetch sports tournaments
export const GET_SPORTS_TOURNAMENTS_INIT = 'GET_SPORTS_TOURNAMENTS_INIT';
export const GET_SPORTS_TOURNAMENTS_START = 'GET_SPORTS_TOURNAMENTS_START';
export const GET_SPORTS_TOURNAMENTS_SUCCESS = 'GET_SPORTS_TOURNAMENTS_SUCCESS';
export const GET_SPORTS_TOURNAMENTS_FAIL = 'GET_SPORTS_TOURNAMENTS_FAIL';
export const GET_INIT_STATE = 'GET_INIT_STATE';

// control selected tournaments
export const ADD_TOURNAMENT = 'ADD_TOURNAMENT';
export const REMOVE_TOURNAMENT = 'REMOVE_TOURNAMENT';

